name: web 
on:
  push:
    branches:
    - main
    - release/*
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: action/checkout@v3
      - name: Install deps
        run: npm install
      - name: Lint
        run: npm run lint
